title: Vincent Lu | AI Research & Developer
page-top-title: Vincent Lu
top-section-bg-text: AI Research & Developer
copyright-text: '&copy; Vincent Lu 2025. All Rights Reserved.'
home-subtitle: Vincent Lu | AI Research & Developer at Fudan University
research-subtitle: '<i class="bi bi-mortarboard-fill me-2"></i> Research Areas'
experience-subtitle: '<i class="bi bi-briefcase-fill me-2"></i> Professional Experience'
awards-subtitle: '<i class="bi bi-award-fill me-2"></i> Awards & Honors'
publications-subtitle: '<i class="bi bi-file-text-fill me-2"></i> Publications'
